**1. Read the CSV File**

In [159]:
import pandas as pd
import numpy as np


df = pd.read_csv("pandas_dataset.csv")

print(" First 5 data")
print(df.head())
original_shape=df.shape
original_shape

 First 5 data
   order_id customer_name     category       product       city  quantity  \
0       NaN           NaN          NaN           NaN        NaN       NaN
1    1001.0         Aarav  Electronics        Laptop  Kathmandu       2.0
2    1002.0          Sita    Furniture  Office Chair   Lalitpur       1.0
3    1003.0         Rohan  Electronics    Headphones  Bhaktapur       3.0
4    1004.0        Anisha     Clothing        Jacket  Kathmandu       2.0

   unit_price order_date     status     sales   profit  discount
0         NaN        NaN        NaN       NaN      NaN       NaN
1     85000.0   1/5/2026  Completed  170000.0  34000.0   17000.0
2     18000.0   1/8/2026  Completed   18000.0   3600.0     900.0
3      4500.0  1/12/2026    Pending   13500.0   2700.0     675.0
4      6500.0  1/15/2026  Completed   13000.0   2600.0     650.0

(27, 12)

In [160]:
df.columns = (df.columns.str.strip().str.lower())

df.columns = (df.columns.str.replace(" ", "_"))
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

**3. Drop Unnecessary Rows**

In [161]:
# dropping first empty row
df = df.dropna(how="all").reset_index(drop=True)
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [162]:

print("Shape after removing unnecessary rows:")
print(df.shape)

Shape after removing unnecessary rows:
(26, 12)

**4. Drop Columns (if needed)**

Since, all column are giving the meaningful information. I dont want to drop any of them.

**5. Count Missing Values**

In [163]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
order_date       0
status           1
sales            3
profit           3
discount         3
dtype: int64

**6. Handle Missing Values**
- Drop rows where `sales` is missing.
- Fill missing values in `profit` using mean and `discount` using median.

In [164]:
sale_drop=df.dropna(subset=['sales'])
df=sale_drop.reset_index(drop=True)
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [165]:
print(df.isnull().sum())

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         0
unit_price       0
order_date       0
status           1
sales            0
profit           1
discount         1
dtype: int64

In [166]:
profit_mean = df["profit"].mean()

discount_median = df["discount"].median()

df["profit"] = df["profit"].fillna(profit_mean)

df["discount"] = df["discount"].fillna(discount_median)

df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [167]:
print(df.isnull().sum())

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         0
unit_price       0
order_date       0
status           1
sales            0
profit           0
discount         0
dtype: int64

**7. Handle Missing Categorical Data**
- Replace missing `customer_name` values with "Unknown".

In [168]:
df["customer_name"] = df["customer_name"].fillna("Unknown")
df.head()
print(df.isnull().sum())

order_id         0
customer_name    0
category         0
product          0
city             1
quantity         0
unit_price       0
order_date       0
status           1
sales            0
profit           0
discount         0
dtype: int64

**8. Detect and Remove Duplicates**
- Identify duplicate rows based on `order_id` using `df.duplicated()`.
- Remove duplicate rows and verify how many were removed.

In [169]:
duplicate_values = df.duplicated(subset=["order_id"])
duplicate_values

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19     True
20     True
21    False
22    False
dtype: bool

In [170]:
duplicate_order_ids = df["order_id"].duplicated()
duplicate_order_ids

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19     True
20     True
21    False
22    False
Name: order_id, dtype: bool

In [171]:
print("Duplicated Order IDs:")
print(duplicate_order_ids)

print("\nNumber of duplicated Order IDs:")
print(duplicate_order_ids.sum())

Duplicated Order IDs:
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19     True
20     True
21    False
22    False
Name: order_id, dtype: bool

Number of duplicated Order IDs:
3

In [172]:
print("\nDuplicate rows:")
print(df[df["order_id"].duplicated(keep=False)])

# Count rows before removing duplicates
before = len(df)

Duplicate rows:
    order_id customer_name     category  product       city  quantity  \
0     1001.0         Aarav  Electronics   Laptop  Kathmandu       2.0
6     1007.0         Nabin    Furniture     Desk   Lalitpur       2.0
11    1013.0        Roshan  Electronics  Monitor   Lalitpur       2.0
18    1001.0         Aarav  Electronics   Laptop  Kathmandu       2.0
19    1007.0         Nabin    Furniture     Desk   Lalitpur       2.0
20    1013.0        Roshan  Electronics  Monitor   Lalitpur       2.0

    unit_price order_date     status     sales   profit  discount
0      85000.0   1/5/2026  Completed  170000.0  34000.0   17000.0
6      25000.0  1/25/2026  Completed   50000.0  10000.0    5000.0
11     28000.0  2/18/2026  Completed   56000.0  11200.0    5600.0
18     85000.0   1/5/2026  Completed  170000.0  34000.0   17000.0
19     25000.0  1/25/2026  Completed   50000.0  10000.0    5000.0
20     28000.0  2/18/2026  Completed   56000.0  11200.0    5600.0

In [173]:
# Remove duplicate Order IDs
df = df.drop_duplicates(
    subset=["order_id"],
    keep="first"
)

# Count rows after removing duplicates
after = len(df)

# Calculate number of rows removed

removed = before - after
print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Number of duplicates removed:", removed)


# Reset index
df = df.reset_index(drop=True)

Rows before removing duplicates: 23
Rows after removing duplicates: 20
Number of duplicates removed: 3

**9. Filtering and Creating New Columns**

In [174]:
print("Orders where unit_price > 20,000:")
print(df[df["unit_price"] > 20000])

print("Orders where unit_price > 10,000 and status is Completed:")
print(df[(df["unit_price"] > 10000) & (df["status"] == "Completed")][["customer_name", "category", "status"]])

df["total_amount"] = df["quantity"] * df["unit_price"] - df["discount"]
print("Dataset with total_amount:")
print(df[["quantity", "unit_price", "discount", "total_amount"]])

df["customer_type"] = np.where(df["quantity"] >= 3, "Bulk Buyer", "Regular Buyer")
print("Dataset with customer_type:")
print(df[["quantity", "customer_type"]])

Orders where unit_price > 20,000:
    order_id customer_name     category       product       city  quantity  \
0     1001.0         Aarav  Electronics        Laptop  Kathmandu       2.0
4     1005.0         Bibek  Electronics  Mobile Phone    Pokhara       1.0
6     1007.0         Nabin    Furniture          Desk   Lalitpur       2.0
11    1013.0        Roshan  Electronics       Monitor   Lalitpur       2.0
15    1017.0         Manoj    Furniture         Table  Kathmandu       1.0

    unit_price order_date     status     sales   profit  discount
0      85000.0   1/5/2026  Completed  170000.0  34000.0   17000.0
4      55000.0  1/20/2026  Cancelled   55000.0  11000.0    5500.0
6      25000.0  1/25/2026  Completed   50000.0  10000.0    5000.0
11     28000.0  2/18/2026  Completed   56000.0  11200.0    5600.0
15     22000.0   3/5/2026  Completed   22000.0   4400.0    1100.0
Orders where unit_price > 10,000 and status is Completed:
   customer_name     category     status
0          Aarav  Electronics  Completed
1           Sita    Furniture  Completed
6          Nabin    Furniture  Completed
11        Roshan  Electronics  Completed
15         Manoj    Furniture  Completed
17          Rita  Electronics  Completed
18        Bikash    Furniture  Completed
Dataset with total_amount:
    quantity  unit_price  discount  total_amount
0        2.0     85000.0   17000.0      153000.0
1        1.0     18000.0     900.0       17100.0
2        3.0      4500.0     675.0       12825.0
3        2.0      6500.0     650.0       12350.0
4        1.0     55000.0    5500.0       49500.0
5        4.0      2200.0     440.0        8360.0
6        2.0     25000.0    5000.0       45000.0
7        3.0      7500.0    1125.0       21375.0
8        2.0      3500.0     350.0        6650.0
9        5.0      1800.0     450.0        8550.0
10       1.0     15000.0     750.0       14250.0
11       2.0     28000.0    5600.0       50400.0
12       3.0      2800.0     420.0        7980.0
13       2.0      4200.0     420.0        7980.0
14       4.0      3500.0     700.0       13300.0
15       1.0     22000.0    1100.0       20900.0
16       2.0      5000.0     500.0        9500.0
17       2.0     12000.0    1200.0       22800.0
18       1.0     18000.0     450.0       17550.0
19       3.0      4500.0     825.0       12675.0
Dataset with customer_type:
    quantity  customer_type
0        2.0  Regular Buyer
1        1.0  Regular Buyer
2        3.0     Bulk Buyer
3        2.0  Regular Buyer
4        1.0  Regular Buyer
5        4.0     Bulk Buyer
6        2.0  Regular Buyer
7        3.0     Bulk Buyer
8        2.0  Regular Buyer
9        5.0     Bulk Buyer
10       1.0  Regular Buyer
11       2.0  Regular Buyer
12       3.0     Bulk Buyer
13       2.0  Regular Buyer
14       4.0     Bulk Buyer
15       1.0  Regular Buyer
16       2.0  Regular Buyer
17       2.0  Regular Buyer
18       1.0  Regular Buyer
19       3.0     Bulk Buyer

In [175]:
print("Shape before cleaning:", original_shape)
print("Shape after cleaning:", df.shape)

Shape before cleaning: (27, 12)
Shape after cleaning: (20, 14)