In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

# project files diractories

In [3]:
RAW_DIR = Path("../data/raw")
PROCESSED_DIR = Path("../data/processed")

In [4]:
customers_raw = pd.read_csv("/home/sanskar/Downloads/python/Data_analysis/project/data/raw/customer_details.csv")
baskets_raw = pd.read_csv("/home/sanskar/Downloads/python/Data_analysis/project/data/raw/basket_details.csv")

# Creating copy

In [5]:
customers = customers_raw.copy(deep=True)
baskets = baskets_raw.copy(deep=True)

print("Customers:", customers.shape)
print("Baskets:", baskets.shape)

Customers: (20000, 4)
Baskets: (15000, 4)

****This makes it easier to compare the original and cleaned data and demonstrate your ETL****

# Perform EDA before cleaning

In [6]:
print("CUSTOMER DATA")
print(customers.info())
print(customers.head())
print(customers.describe(include="all"))

CUSTOMER DATA
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   20000 non-null  int64
 1   sex           20000 non-null  str
 2   customer_age  20000 non-null  float64
 3   tenure        20000 non-null  int64
dtypes: float64(1), int64(2), str(1)
memory usage: 625.1 KB
None
   customer_id   sex  customer_age  tenure
0      9798859  Male          44.0      93
1     11413563  Male          36.0      65
2       818195  Male          35.0     129
3     12049009  Male          33.0      58
4     10083045  Male          42.0      88
         customer_id    sex  customer_age        tenure
count   2.000000e+04  20000  20000.000000  20000.000000
unique           NaN      4           NaN           NaN
top              NaN   Male           NaN           NaN
freq             NaN  15322           NaN           NaN
mean    1.760040e+07    NaN    262.222550     44.396800
std     8.679505e+06    NaN    604.321589     31.998376
min     2.093000e+03    NaN    -34.000000      4.000000
25%     1.188115e+07    NaN     29.000000     21.000000
50%     1.560912e+07    NaN     38.000000     35.000000
75%     2.228484e+07    NaN    123.000000     60.000000
max     4.462566e+07    NaN   2022.000000    133.000000

In [7]:
print("\nBASKET DATA")
print(baskets.info())
print(baskets.head())
print(baskets.describe(include="all"))

BASKET DATA
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   15000 non-null  int64
 1   product_id    15000 non-null  int64
 2   basket_date   15000 non-null  str
 3   basket_count  15000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 468.9 KB
None
   customer_id  product_id basket_date  basket_count
0     42366585    41475073  2019-06-19             2
1     35956841    43279538  2019-06-19             2
2     26139578    31715598  2019-06-19             3
3      3262253    47880260  2019-06-19             2
4     20056678    44747002  2019-06-19             2
         customer_id    product_id basket_date  basket_count
count   1.500000e+04  1.500000e+04       15000  15000.000000
unique           NaN           NaN          31           NaN
top              NaN           NaN  2019-05-27           NaN
freq             NaN           NaN        1617           NaN
mean    1.808567e+07  3.269771e+07         NaN      2.153733
std     1.233000e+07  1.629455e+07         NaN      0.517929
min     4.784000e+03  4.939000e+04         NaN      2.000000
25%     8.659327e+06  3.137412e+07         NaN      2.000000
50%     1.520775e+07  3.694759e+07         NaN      2.000000
75%     2.663904e+07  4.502408e+07         NaN      2.000000
max     4.460824e+07  5.579097e+07         NaN     10.000000

# Check missing values

In [8]:
print("Customer missing values:")
print(customers.isnull().sum())

print("\nBasket missing values:")
print(baskets.isnull().sum())

Customer missing values:
customer_id     0
sex             0
customer_age    0
tenure          0
dtype: int64

Basket missing values:
customer_id     0
product_id      0
basket_date     0
basket_count    0
dtype: int64

Current file contain no missing values.

However, zero missing values does not mean the data is clean. A field can contain an invalid value without being empty.

# Check duplicates

In [9]:
print(
    "Duplicate customer rows:",
    customers.duplicated().sum()
)

Duplicate customer rows: 0

In [10]:
print(
    "Duplicate customer IDs:",
    customers["customer_id"].duplicated().sum()
)

Duplicate customer IDs: 0

In [11]:
print(
    "Duplicate basket rows:",
    baskets.duplicated().sum()
)

Duplicate basket rows: 0

# Examine categorical values

In [12]:
print(customers["sex"].value_counts(dropna=False))

sex
Male                15322
Female               4669
kvkktalepsilindi        8
UNKNOWN                 1
Name: count, dtype: int64

In [13]:
print(
    customers["customer_age"]
    .value_counts()
    .sort_values(ascending=False)
    .head(15)
)

customer_age
123.0     4539
2022.0    2102
29.0       801
5.0        710
30.0       695
31.0       684
28.0       682
27.0       664
32.0       584
26.0       582
33.0       539
34.0       539
25.0       520
35.0       519
24.0       511
Name: count, dtype: int64

In [14]:
print("\nAge distribution:")
print(customers["customer_age"].describe())

Age distribution:
count    20000.000000
mean       262.222550
std        604.321589
min        -34.000000
25%         29.000000
50%         38.000000
75%        123.000000
max       2022.000000
Name: customer_age, dtype: float64

In [15]:
print("\nTenure distribution:")
print(customers["tenure"].describe())

print("\nBasket count distribution:")
print(baskets["basket_count"].value_counts().sort_index())

Tenure distribution:
count    20000.000000
mean        44.396800
std         31.998376
min          4.000000
25%         21.000000
50%         35.000000
75%         60.000000
max        133.000000
Name: tenure, dtype: float64

Basket count distribution:
basket_count
2     13323
3      1279
4       268
5        76
6        27
7        13
8        10
9         2
10        2
Name: count, dtype: int64

# Clean the customer dataset

In [16]:
customers.columns = (
    customers.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
customers.head()

   customer_id   sex  customer_age  tenure
0      9798859  Male          44.0      93
1     11413563  Male          36.0      65
2       818195  Male          35.0     129
3     12049009  Male          33.0      58
4     10083045  Male          42.0      88

In [17]:
baskets.columns = (
    baskets.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
baskets.head()

   customer_id  product_id basket_date  basket_count
0     42366585    41475073  2019-06-19             2
1     35956841    43279538  2019-06-19             2
2     26139578    31715598  2019-06-19             3
3      3262253    47880260  2019-06-19             2
4     20056678    44747002  2019-06-19             2

# Correct customer ages

In [18]:
# Convert age to a numeric type.
customers["customer_age"] = pd.to_numeric(
    customers["customer_age"],
)

# Record the original age values before cleaning.
customers["customer_age_original"] = (
    customers["customer_age"]
)

In [19]:
# Count ages outside our chosen validation range.
invalid_age_mask = (
    (customers["customer_age"] < 0)
    | (customers["customer_age"] > 100)
)

print("Invalid age records:", invalid_age_mask.sum())

print("\nInvalid age values:")
print(
    customers.loc[
        invalid_age_mask,
        "customer_age"
    ].value_counts().sort_index()
)

Invalid age records: 6707

Invalid age values:
customer_age
-34.0         1
 101.0        2
 103.0        2
 112.0        2
 115.0        1
 116.0        2
 117.0        5
 118.0        7
 119.0        4
 120.0       10
 121.0        5
 122.0       16
 123.0     4539
 124.0        5
 127.0        1
 130.0        1
 139.0        1
 149.0        1
 2022.0    2102
Name: count, dtype: int64

In [20]:
# Preserve the original values for auditing.
customers["customer_age_original"] = customers["customer_age"].copy()

# Convert the age column to numeric.a
customers["customer_age"] = pd.to_numeric(
    customers["customer_age"],
    errors="coerce"
)

# Identify ages outside the validation range.
invalid_age_mask = ~customers["customer_age"].between(0, 100)

# Report the number of invalid values before modifying them.
print("Invalid ages before cleaning:", invalid_age_mask.sum())

# Mark invalid ages as missing instead of guessing their correct values.
customers.loc[invalid_age_mask, "customer_age"] = np.nan

# Verify the result.
print("\nMissing ages after cleaning:")
print(customers["customer_age"].isna().sum())

print("\nCleaned age statistics:")
print(customers["customer_age"].describe())

Missing ages after cleaning:
6707

Age statistics after cleaning:
count    13293.000000
mean        32.209133
std         10.791678
min          3.000000
25%         27.000000
50%         31.000000
75%         38.000000
max        100.000000
Name: customer_age, dtype: float64

# Standardize the gender column

In [21]:
customers["sex"] = (
    customers["sex"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [22]:
customers["sex"] = customers["sex"].replace({
    "male": "Male",
    "female": "Female",
    "unknown": "Unknown",
    "kvkktalepsilindi": "Unknown"
})

In [23]:
customers["sex"].unique()

<StringArray>
['Male', 'Female', 'Unknown']
Length: 3, dtype: string

In [24]:
print(customers["tenure"].describe())

count    20000.000000
mean        44.396800
std         31.998376
min          4.000000
25%         21.000000
50%         35.000000
75%         60.000000
max        133.000000
Name: tenure, dtype: float64

In [25]:
print(
    customers.loc[
        customers["tenure"] > 120,
        ["customer_id", "tenure"]
    ].head(20)
)

     customer_id  tenure
2         818195     129
6         819721     129
16        831271     129
26        593411     130
27        844249     129
53        860990     129
98       1052163     127
110       875329     129
115       247695     130
121       851739     129
139      1077559     127
142      1101723     127
143       869421     129
147       551355     130
152       825111     129
166       845229     129
167       268289     130
169       828364     129
170        27867     131
172        25012     131

# Clean the basket dataset

In [26]:
baskets["basket_date"] = pd.to_datetime(
    baskets["basket_date"])

print("Invalid dates:", baskets["basket_date"].isna().sum())

Invalid dates: 0

# Validate numeric columns

In [27]:
baskets["customer_id"] = pd.to_numeric(
    baskets["customer_id"],
    errors="coerce"
).astype("Int64")

In [28]:
baskets["product_id"] = pd.to_numeric(
    baskets["product_id"],
    errors="coerce"
).astype("Int64")

baskets["basket_count"] = pd.to_numeric(
    baskets["basket_count"],
    errors="coerce"
).astype("Int64")

In [29]:
print(baskets.isnull().sum())

print(
    baskets.loc[
        baskets["basket_count"].isna()
        | (baskets["basket_count"] <= 0)
    ]
)

customer_id     0
product_id      0
basket_date     0
basket_count    0
dtype: int64
Empty DataFrame
Columns: [customer_id, product_id, basket_date, basket_count]
Index: []

# Investigate duplicate basket records

In [30]:
duplicate_key_mask = baskets.duplicated(
    subset=["customer_id", "product_id", "basket_date"],
    keep=False
)

print(duplicate_key_mask.sum())

0

# Investigate the customer ID mismatch

In [31]:
customer_ids = set(customers_raw["customer_id"])
basket_customer_ids = set(baskets_raw["customer_id"])

matched_ids = customer_ids & basket_customer_ids
unmatched_basket_ids = basket_customer_ids - customer_ids

print("Unique customers:", len(customer_ids))
print("Unique basket customers:", len(basket_customer_ids))
print("Matching customer IDs:", len(matched_ids))
print("Unmatched basket customer IDs:", len(unmatched_basket_ids))

print(
    "Basket rows without a matching customer:",
    (~baskets_raw["customer_id"].isin(customer_ids)).sum()
)

Unique customers: 20000
Unique basket customers: 13871
Matching customer IDs: 64
Unmatched basket customer IDs: 13807
Basket rows without a matching customer: 14928

# Validate and export the cleaned data

In [32]:
# Customer validation
assert customers["customer_id"].notna().all()
assert customers["customer_id"].is_unique

# Age validation
assert (
    customers["customer_age"].dropna().between(0, 100).all()
)

# Basket validation
assert baskets["customer_id"].notna().all()
assert baskets["product_id"].notna().all()
assert baskets["basket_date"].notna().all()

assert (
    baskets["basket_count"].dropna().gt(0).all()
)

print("Basic validation passed.")

Basic validation passed.

In [33]:
customers_final = customers.drop(
    columns=["customer_age_original"],
)

customers_final.to_csv(
    PROCESSED_DIR / "customers_cleaned.csv",
    index=False
)

baskets.to_csv(
    PROCESSED_DIR / "baskets_cleaned.csv",
    index=False
)

print("Cleaned datasets exported successfully.")

Cleaned datasets exported successfully.

In [34]:
# Display sample customer IDs
print("Customer IDs:")
print(customers_raw["customer_id"].head(15).tolist())

# Display sample basket customer IDs
print("\nBasket customer IDs:")
print(baskets_raw["customer_id"].head(15).tolist())

# Find matching customer IDs
customer_ids = set(customers_raw["customer_id"])
basket_customer_ids = set(baskets_raw["customer_id"])

matching_ids = customer_ids.intersection(basket_customer_ids)

print("\nSample matching IDs:")
print(list(matching_ids)[:20])

# Find unmatched basket customer IDs
unmatched_ids = basket_customer_ids - customer_ids

print("\nSample unmatched IDs:")
print(list(unmatched_ids)[:20])

Customer IDs:
[9798859, 11413563, 818195, 12049009, 10083045, 11248447, 819721, 4713723, 11141669, 10844015, 5012539, 11351893, 4815027, 11320883, 4306642]

Basket customer IDs:
[42366585, 35956841, 26139578, 3262253, 20056678, 32037116, 17565651, 42079380, 25533477, 10385144, 5216868, 9036689, 20265792, 34654104, 31159555]

Sample matching IDs:
[25055107, 4238087, 16398473, 20789769, 12901520, 13776147, 11346069, 9500953, 22524187, 9654043, 43280797, 4193819, 36623391, 4643359, 851739, 16029475, 10439331, 20236456, 10394153, 9804585]

Sample unmatched IDs:
[23396352, 4030464, 6389762, 4194306, 4947972, 20742148, 41713670, 1146890, 3637258, 16941074, 30638099, 12484629, 18907162, 11534362, 41877533, 14581789, 37552161, 40402980, 12976168, 20021289]

# Now using the processed data

In [36]:
customers_check = pd.read_csv(
    PROCESSED_DIR / "customers_cleaned.csv"
)

baskets_check = pd.read_csv(
    PROCESSED_DIR / "baskets_cleaned.csv"
)

In [38]:
print("CUSTOMER DATASET")
print("Shape:", customers_check.shape)
print("\nMissing values:")
print(customers_check.isna().sum())

CUSTOMER DATASET
Shape: (20000, 4)

Missing values:
customer_id        0
sex                0
customer_age    6707
tenure             0
dtype: int64

In [39]:
print("\nBASKET DATASET")
print("Shape:", baskets_check.shape)
print("\nMissing values:")
print(baskets_check.isna().sum())

BASKET DATASET
Shape: (15000, 4)

Missing values:
customer_id     0
product_id      0
basket_date     0
basket_count    0
dtype: int64